# Generated by Django 5.0.2 on 2024-06-04 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Enter the 16-digit card number', max_length=20, verbose_name='Card Number')),
                ('name', models.CharField(help_text='Enter the name as it appears on the card', max_length=50, verbose_name='Name on Card')),
                ('due_date', models.DateField(help_text="Enter the card's expiration date", verbose_name='Due Date')),
                ('cvc', models.CharField(help_text='Enter the 3 or 4-digit security code', max_length=4, verbose_name='CVC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
