# Generated by Django 5.0.2 on 2024-06-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.CharField(help_text="Enter the card's expiration date", max_length=20, verbose_name='Due Date'),
        ),
    ]
