# Generated by Django 5.0.2 on 2024-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='access_token',
            field=models.CharField(max_length=1000),
        ),
    ]
