# Generated by Django 5.0.2 on 2024-05-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraccesstoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='default_state', max_length=50),
            preserve_default=False,
        ),
    ]
