# Generated by Django 5.0.2 on 2024-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraddress_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesstoken',
            name='expiration',
        ),
        migrations.AddField(
            model_name='useraccesstoken',
            name='refresh_token',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
