# Generated by Django 5.0.2 on 2024-05-31 21:13

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category_alter_productcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(max_length=255, storage=apps.products.models.CloudinaryStorage(folder='projects/ecommerce/categories/icons'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, storage=apps.products.models.CloudinaryStorage(folder='projects/ecommerce/products/images'), upload_to=''),
        ),
    ]
